apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}eureka-dev-svc
spec:
  selector:
    app: {{ .Values.appName }}
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.targetPort }}